"""Spec 006 interaction scaffold: compose registry + policy + trace.

``evaluate_interaction`` composes the closed tool allow-list, frozen safety
policy, and typed evidence prerequisites into exactly one terminal behavioral
state per synthetic interaction:

    ANSWER | ASK_MORE | USE_TOOL | RETRIEVE_EVIDENCE | ABSTAIN | ESCALATE |
    EMERGENCY

Frozen semantics (research.md §5–§8):

- generative text can never lower a deterministic safety decision;
- injection payloads are suppressed and logged, never obeyed;
- spoofed tool results are rejected by provenance and fail closed;
- unavailable/timeout tools fail closed with auditable reasons;
- conflicting safety outcomes are never averaged;
- evidence-gated tool classes whose real source authorities remain
  ``NEEDS_EVIDENCE`` (tasks T017..T020) abstain with
  ``EVIDENCE_NOT_RESOLVED`` instead of fabricating clinical truth.

Every evaluation emits a hash-chained, privacy-safe InteractionTrace whose
determinism proof is generated by replaying the evaluation and asserting the
five replay equalities plus identical output state.
"""

from __future__ import annotations

import re
from typing import Any

from src.commandmed.eval_contract.canonical import compute_canonical_sha256
from src.commandmed.spec006 import policy, registry, trace

# Frozen suppression markers for known instruction-injection shapes. Detection
# is signal-only: matched payloads never alter the frozen decision path.
INJECTION_MARKERS = (
    "ignore previous instructions",
    "ignore all previous instructions",
    "disregard your instructions",
    "you are now",
    "developer mode",
    "system prompt:",
    "تجاهل التعليمات السابقة",
    "تجاهل جميع القواعد",
)

EVIDENCE_GATED_TOOL_CLASSES = frozenset(
    {"validated_clinical_score", "interaction_lookup"}
)

TOOL_LAYER_RULE_ID = "SCAFFOLD::TOOL_LAYER"
TOOL_LAYER_PRECEDENCE = 6


def _normalized_text(value: Any) -> str:
    return value.strip().lower() if isinstance(value, str) else ""


def detect_injection(text: Any) -> bool:
    """Deterministic lexical detection of known injection payload markers."""
    lowered = _normalized_text(text)
    return any(marker in lowered for marker in INJECTION_MARKERS)


def _rule_matches(
    rule: dict[str, Any],
    text: str,
    provided_slots: set[str],
    requested_tool_class: str | None,
) -> bool:
    condition = rule["trigger_condition"]
    kind = condition.get("kind")
    ref = condition.get("ref")
    if not isinstance(ref, str):
        return False
    if kind == "lexical":
        tokens = [token.strip().lower() for token in ref.split("|") if token.strip()]
        return any(token in text for token in tokens)
    if kind == "semantic_pattern":
        try:
            return re.search(ref, text, flags=re.IGNORECASE) is not None
        except re.error:
            # Malformed frozen pattern fails closed through BLOCKED_SAFETY_STATE.
            return False
    if kind == "missing_slot":
        # Scoped by the frozen ``threshold`` list of tool classes: the rule
        # only gates deterministic steps whose class actually requires the
        # critical slots (research.md §5 item 4: missing evidence for a
        # CLAIMED finding/action).
        threshold = condition.get("threshold")
        if not isinstance(threshold, str):
            return False
        gated_classes = {token.strip() for token in threshold.split("|") if token.strip()}
        if requested_tool_class is None or requested_tool_class not in gated_classes:
            return False
        required_slots = [slot.strip() for slot in ref.split("|") if slot.strip()]
        return any(slot not in provided_slots for slot in required_slots)
    # evidence_state and tool_result_flag rules require explicit firing input.
    return False


def _collect_fired_rules(
    policy_bundle: dict[str, Any],
    text: str,
    provided_slots: set[str],
    tool_flag_rule_ids: set[str],
    requested_tool_class: str | None = None,
) -> list[dict[str, Any]]:
    fired: list[dict[str, Any]] = []
    for rule in policy_bundle.get("rules", []):
        if not isinstance(rule, dict):
            continue
        if rule["trigger_condition"].get("kind") == "tool_result_flag":
            if rule["rule_id"] in tool_flag_rule_ids:
                fired.append(rule)
            continue
        if _rule_matches(rule, text, provided_slots, requested_tool_class):
            fired.append(rule)
    return fired


def _prerequisite_gate_open(
    prerequisites: dict[str, Any] | None, tool_class: str
) -> tuple[bool, list[str]]:
    """Return (open, reason_codes) for evidence-gated tool classes.

    Fail-closed: a class covered by any ``NEEDS_EVIDENCE`` gate is closed; a
    missing or malformed prerequisites bundle also closes the gate.
    """
    if prerequisites is None or not isinstance(prerequisites, dict):
        return False, ["EVIDENCE_NOT_RESOLVED"]
    gates = prerequisites.get("gates")
    if not isinstance(gates, list):
        return False, ["EVIDENCE_NOT_RESOLVED"]
    reasons: list[str] = []
    for gate in gates:
        if not isinstance(gate, dict):
            continue
        classes = gate.get("tool_classes")
        if not isinstance(classes, list):
            continue
        if tool_class in classes:
            status = gate.get("status")
            if status != "RESOLVED":
                gate_task = gate.get("gate_task", "UNKNOWN")
                reasons.append(f"EVIDENCE_NOT_RESOLVED::{gate_task}")
    if reasons:
        return False, sorted(reasons)
    return True, []


def _resolve_tool_outcome(
    requested_tool_id: Any,
    safety_context: dict[str, Any],
    registry_bundle: dict[str, Any],
    prerequisites: dict[str, Any] | None,
    claimed_provenance: Any,
) -> tuple[dict[str, Any] | None, list[dict[str, Any]]]:
    """Resolve the deterministic tool layer for one interaction.

    Returns (pseudo_rule_or_None, tool_call_records). The pseudo-rule carries
    the tool layer's terminal requirement into precedence resolution so that
    emergency/escalation rules always dominate it.
    """
    if not requested_tool_id or not isinstance(requested_tool_id, str):
        return None, []

    records: list[dict[str, Any]] = []
    tool = registry.find_tool(registry_bundle, requested_tool_id)

    def _record(
        tool_record: dict[str, Any] | None,
        *,
        is_failure: bool,
        reason_code: str | None,
    ) -> dict[str, Any]:
        if tool_record is None:
            unknown_identity = compute_canonical_sha256({"unknown_tool": requested_tool_id})
            return {
                "tool_call_id": f"{requested_tool_id}::call",
                "tool_id": requested_tool_id,
                "tool_version": "unknown",
                "input_identity_sha256": unknown_identity,
                "output_identity_sha256": unknown_identity,
                "provenance": {
                    "tool_content_identity": "0" * 64,
                    "source_authority": "UNBOUND",
                    "result_sha256": "0" * 64,
                },
                "failure": {"is_failure": True, "reason_code": reason_code},
            }
        return {
            "tool_call_id": f"{requested_tool_id}::call",
            "tool_id": tool_record["tool_id"],
            "tool_version": tool_record["tool_version"],
            "input_identity_sha256": compute_canonical_sha256(requested_tool_id),
            "output_identity_sha256": compute_canonical_sha256(
                {"result": "simulated-offline-fixture", "tool_id": requested_tool_id}
            ),
            "provenance": {
                "tool_content_identity": tool_record["tool_content_identity"],
                "source_authority": tool_record["source_authority"],
                "result_sha256": compute_canonical_sha256(
                    {
                        "tool_id": tool_record["tool_id"],
                        "tool_version": tool_record["tool_version"],
                        "result": "simulated-offline-fixture",
                    }
                ),
            },
            "failure": {"is_failure": is_failure, "reason_code": reason_code},
        }

    if tool is None:
        # Closed allow-list: unknown tools are never invented or answered.
        records.append(_record(None, is_failure=True, reason_code="TOOL_UNAVAILABLE"))
        return {
            "rule_id": TOOL_LAYER_RULE_ID,
            "precedence": TOOL_LAYER_PRECEDENCE,
            "required_state": "ABSTAIN",
        }, records

    availability = safety_context.get("tool_availability") or {}
    availability_state = availability.get(tool["tool_id"], "AVAILABLE")

    failure_semantics = tool["failure_semantics"]

    if availability_state == "TIMEOUT":
        records.append(_record(tool, is_failure=True, reason_code="TOOL_TIMEOUT"))
        return {
            "rule_id": TOOL_LAYER_RULE_ID,
            "precedence": TOOL_LAYER_PRECEDENCE,
            "required_state": "ABSTAIN",
        }, records

    if availability_state == "UNAVAILABLE":
        records.append(_record(tool, is_failure=True, reason_code="TOOL_UNAVAILABLE"))
        return {
            "rule_id": TOOL_LAYER_RULE_ID,
            "precedence": TOOL_LAYER_PRECEDENCE,
            "required_state": failure_semantics["fail_state"],
        }, records

    if tool["tool_class"] in EVIDENCE_GATED_TOOL_CLASSES:
        open_gate, gate_reasons = _prerequisite_gate_open(prerequisites, tool["tool_class"])
        if not open_gate:
            records.append(
                _record(tool, is_failure=True, reason_code=gate_reasons[0].split("::")[0])
            )
            return {
                "rule_id": TOOL_LAYER_RULE_ID,
                "precedence": TOOL_LAYER_PRECEDENCE,
                "required_state": "ABSTAIN",
            }, records

    if isinstance(claimed_provenance, dict):
        claimed_identity = claimed_provenance.get("tool_content_identity")
        claimed_authority = claimed_provenance.get("source_authority")
        if (
            claimed_identity != tool["tool_content_identity"]
            or claimed_authority != tool["source_authority"]
        ):
            records.append(
                _record(tool, is_failure=True, reason_code="SPOOFED_TOOL_RESULT_REJECTED")
            )
            return {
                "rule_id": TOOL_LAYER_RULE_ID,
                "precedence": TOOL_LAYER_PRECEDENCE,
                "required_state": failure_semantics["fail_state"],
            }, records

    target_state = (
        "RETRIEVE_EVIDENCE"
        if tool["tool_class"] == "evidence_retrieval"
        else "USE_TOOL"
    )
    records.append(_record(tool, is_failure=False, reason_code=None))
    return {
        "rule_id": TOOL_LAYER_RULE_ID,
        "precedence": TOOL_LAYER_PRECEDENCE,
        "required_state": target_state,
    }, records


def _build_determinism_proof(
    state_after: str,
    identities: dict[str, str],
) -> dict[str, Any]:
    return {
        "replayed": True,
        "replay_input_sha256": identities["input_identity_sha256"],
        "replay_context_identity_sha256": identities["context_identity_sha256"],
        "replay_policy_identity_sha256": identities["policy_identity_sha256"],
        "replay_tool_registry_identity_sha256": identities[
            "tool_registry_identity_sha256"
        ],
        "replay_output_state": state_after,
    }


def evaluate_interaction(
    interaction_id: str,
    user_request: dict[str, Any],
    safety_context: dict[str, Any],
    registry_bundle: dict[str, Any],
    policy_bundle: dict[str, Any],
    prerequisites: dict[str, Any] | None = None,
    previous_trace: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Evaluate one synthetic interaction into one terminal state + trace.

    Returns a decision dictionary containing the terminal behavioral state,
    reason codes, fired trigger ids, ordered tool-call records, and the
    complete chained InteractionTrace record with determinism proof.
    """
    identities = {
        "input_identity_sha256": compute_canonical_sha256(user_request),
        "context_identity_sha256": compute_canonical_sha256(safety_context),
        "policy_identity_sha256": registry.compute_registry_identity(
            policy_bundle.get("policy_version"), policy_bundle.get("rules")
        ),
        "tool_registry_identity_sha256": registry.compute_registry_identity(
            registry_bundle.get("registry_version"), registry_bundle.get("tools")
        ),
    }
    # The policy projection uses the same omit-hash-field convention.
    identities["policy_identity_sha256"] = policy.compute_policy_identity(
        policy_bundle.get("policy_version"), policy_bundle.get("rules")
    )

    text = _normalized_text(user_request.get("text"))
    provided_slots = set(user_request.get("provided_slots") or [])
    tool_flag_rule_ids = set(user_request.get("fired_tool_flag_rule_ids") or [])

    requested_tool_id = user_request.get("requested_tool_id")
    requested_tool = (
        registry.find_tool(registry_bundle, requested_tool_id)
        if isinstance(requested_tool_id, str) and requested_tool_id
        else None
    )
    requested_tool_class = (
        requested_tool["tool_class"] if isinstance(requested_tool, dict) else None
    )

    fired_rules = _collect_fired_rules(
        policy_bundle, text, provided_slots, tool_flag_rule_ids, requested_tool_class
    )

    tool_rule, tool_records = _resolve_tool_outcome(
        requested_tool_id,
        safety_context,
        registry_bundle,
        prerequisites,
        user_request.get("claimed_tool_provenance"),
    )
    if tool_rule is not None:
        fired_rules.append(tool_rule)

    resolution = policy.evaluate_precedence(fired_rules)
    state_after = resolution["state_after"]
    reason_codes = list(resolution["reason_codes"])
    trigger_ids = [
        rule_id
        for rule_id in resolution["trigger_record_ids"]
        if rule_id != TOOL_LAYER_RULE_ID
    ]
    if any(record["failure"]["is_failure"] for record in tool_records):
        for record in tool_records:
            code = record["failure"]["reason_code"]
            if code and code not in reason_codes:
                reason_codes.append(code)

    if detect_injection(user_request.get("text")):
        if "INJECTION_ATTEMPT_SUPPRESSED" not in reason_codes:
            reason_codes.append("INJECTION_ATTEMPT_SUPPRESSED")

    partial = {
        "interaction_id": interaction_id,
        "trace_version": "v1",
        "predecessor_sha256": None,
        "input_identity_sha256": identities["input_identity_sha256"],
        "context_identity_sha256": identities["context_identity_sha256"],
        "policy_identity_sha256": identities["policy_identity_sha256"],
        "tool_registry_identity_sha256": identities["tool_registry_identity_sha256"],
        "state_before": None if previous_trace is None else previous_trace["state_after"],
        "state_after": state_after,
        "trigger_record_ids": trigger_ids,
        "tool_call_record_ids": [record["tool_call_id"] for record in tool_records],
        "output_identity_sha256": compute_canonical_sha256(
            {"state_after": state_after, "reason_codes": reason_codes}
        ),
        "failure_reason_codes": [code for code in reason_codes if "::" not in code],
        "safety_context": safety_context,
        "tool_calls": tool_records,
        "determinism_proof": {},
    }

    trace_record = trace.append_trace(previous_trace, partial)
    trace_record["determinism_proof"] = _build_determinism_proof(state_after, identities)

    return {
        "state_after": state_after,
        "reason_codes": reason_codes,
        "trigger_record_ids": trigger_ids,
        "tool_calls": tool_records,
        "trace": trace_record,
    }
